<?php
/**
 * @file
 * Code for the bb_misc feature.
 */

include_once 'bb_misc.features.inc';

function computed_field_field_total_orders_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $entity_field[0]['value'] = db_query("SELECT COUNT(order_id) FROM {commerce_order} WHERE status = 'completed' AND uid = :uid", array(':uid' => $entity->uid))->fetchField(0);
}

/**
 * Implements hook_permission().
 *
 * Define permission to allow editing custom fields:
 * * field_customs_id
 */
function bb_misc_permission() {
  return array(
    'view own field_customs_id' => array('title' => t('View own field_customs_id')),
    // there oughtn't be a circumstance for editing one's own customs id... but...
    'edit own field_customs_id' => array('title' => t('Edit own field_customs_id')),
    'view any field_customs_id' => array('title' => t('View any field_customs_id')),
    'edit any field_customs_id' => array('title' => t('Edit any field_customs_id')),
  );
}

/**
 * Implements hook_field_access().
 *
 * Special permissions for:
 * * field_customs_id
 */
function bb_misc_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'field_customs_id') {
    if (user_access('edit any commerce_order entity of bundle commerce_order') || user_access('administer commerce_order entities')) {
      return TRUE;
    }
    $context = 'any';
    if ($entity_type == 'commerce_order' && $entity && $entity->uid == $account->uid) {
      $context = 'own';
    }
    $perm = $op . ' ' . $context . ' field_customs_id';
    $access = user_access($perm, $account);
    return $access;
  }
  return TRUE;
}

/*
 * Implements hook_entity_presave().
 *
 * @todo docs
 */
function bb_misc_entity_presave($entity, $type) {
  if ($type == 'commerce_order' && arg(3) == 'fulfil_international') {
    if (is_array($entity->field_customs_id) && !empty($entity->field_customs_id['und']) && !empty(trim($entity->field_customs_id['und'][0]['value']))) {
      $entity->status = 'completed';
      if (empty($entity->field_shipped_date)) {
        $entity->field_shipped_date['und'][0]['value'] = date("Y-m-d H:i:s");
      }
    } else {
      $entity->status = 'processing';
      unset($entity->field_shipped_date['und']);
    }
  }
}
